### PR TITLE
Add french translations

### PR DESCRIPTION
**Pull request by MGLL**
Hello,

I did a french translation and adjusted the implementation. If you are interested. 

- Add french translations
- Add missing translations
- Tweak translations config

Would it be possible to extend a bit the documentation for environment configuration?

### CODE REVIEW

**Comment by xgp** [comment]
> Would it be possible to extend a bit the documentation for environment configuration?

Yes. Please include in the PR.

Thanks for the translations!

**Comment by MGLL** [comment]
Sadly I didn't found how to do it (tried to create an .env file but it wasn't taken into account).
So I just modified locally the config.ts so I could test the translation.

Also, I noticed that on page reload, active language was lost, so I did a workaround through localStorage in i18n.ts. Don't know if it's the best way to do it.

**Comment by xgp** [comment]
@MGLL Sorry for the delay. Hope you are having a good holiday season.

The way `locale` in the config gets populated is here:
https://github.com/p2-inc/phasetwo-admin-portal/blob/main/ext/main/java/io/phasetwo/portal/PortalResourceProvider.java#L171-L180

The code that renders the initial HTML creates an `environment` variable, which should not change on reload. If that is happening, we should figure out how that is happening and fix it.

**Comment by MGLL** [comment]
@xgp No problem, yes I hope you too.

Sorry, I wasn't completely clear. 
The issue I noticed is that i18n.ts is reloaded every time on page reload.

So, every time the translation switches back to English (I don't know why).
But if I go back in the user's profile, the locale is pulled again (to populate selectedLocale), and translation changes back to the correct language.

As a workaround, I populate the localeStorage with the user's locale (on locale change and login), and I made i18n.ts rely on it to correctly display the correct language everywhere, even on page reload.

As originally, I'm not a FE developer, I'm not sure that's the best way. I will wait @pnzrr review and see.

**Comment by pnzrr** [comment]
@MGLL thank you for the great PR. I tweaked a couple things 
- formatting of function calls
- moved the initial check into the `App` layer, so that its not just the organizations view
- adjusted initial load to pull in the locale 

Give everything a test as well to make sure it works. Other than that I think its pretty much there 🙌

**Comment by MGLL** [comment]
Hello @pnzrr thanks for the feedback and the adjustments 🙌 

I did some tests and it seems to works fine. I have added some translations I missed (in toasts and placeholders). 

I wanted to ask, is there a way to populate the `environment: Environment` from a .env file for local development ? (I'm currently modifying the `initialEnvironment: Environment` for development.)

From what I see, I guess it's populated by the keycloak server when its packaged in it (with `PortalResourceProvider`).

**Comment by pnzrr** [comment]
Great to hear no issues. As of now, modifying that config the way you are doing is ok for local dev. Since it gets injected by the server and that doesn't necessarily happen on local, it's a simple way to mock what you need.

**Review by xgp — APPROVED** [review]

**Comment by xgp** [comment]
@MGLL Merci!

**Pull request merged**
